import { Book } from "./data";
export const books: Book[] = [
    {
        id: 1,
        title: "The Great Gatsby",
        authors_ids: "1,2",
        item_type: "book",
        published_date: "1925-04-10",
    },
    {
        id: 2,
        title: "To Kill a Mockingbird",
        authors_ids: "3",
        item_type: "book",
        published_date: "1960-07-11",
    },
    {
        id: 3,
        title: "Nature",
        authors_ids: "4,5",
        item_type: "journal",
        published_date: "1869-11-04",
    },
    {
        id: 4,
        title: "Harry Potter and the Philosopher's Stone",
        authors_ids: "1",
        item_type: "book",
        published_date: "1997-06-26",
    },
    {
        id: 5,
        title: "Pride and Prejudice",
        authors_ids: "2",
        item_type: "book",
        published_date: "1813-01-28",
    },
    {
        id: 6,
        title: "The Catcher in the Rye",
        authors_ids: "3",
        item_type: "book",
        published_date: "1951-07-16",
    },
    {
        id: 7,
        title: "1984",
        authors_ids: "4",
        item_type: "book",
        published_date: "1949-06-08",
    },
    {
        id: 8,
        title: "The Hobbit",
        authors_ids: "5",
        item_type: "book",
        published_date: "1937-09-21",
    },
    {
        id: 9,
        title: "Moby-Dick",
        authors_ids: "1",
        item_type: "book",
        published_date: "1851-10-18",
    },
    {
        id: 10,
        title: "The Lord of the Rings",
        authors_ids: "2",
        item_type: "book",
        published_date: "1954-07-29",
    },
    {
        id: 11,
        title: "The Chronicles of Narnia",
        authors_ids: "3",
        item_type: "book",
        published_date: "1950-10-16",
    },
    {
        id: 12,
        title: "War and Peace",
        authors_ids: "4",
        item_type: "book",
        published_date: "1869-01-01",
    },
    {
        id: 13,
        title: "Frankenstein",
        authors_ids: "5",
        item_type: "book",
        published_date: "1818-01-01",
    },
    {
        id: 14,
        title: "Crime and Punishment",
        authors_ids: "1",
        item_type: "book",
        published_date: "1866-01-01",
    },
    {
        id: 15,
        title: "Wuthering Heights",
        authors_ids: "2",
        item_type: "book",
        published_date: "1847-01-01",
    },
    {
        id: 16,
        title: "The Picture of Dorian Gray",
        authors_ids: "3",
        item_type: "book",
        published_date: "1890-01-01",
    },
    {
        id: 17,
        title: "Jane Eyre",
        authors_ids: "4",
        item_type: "book",
        published_date: "1847-10-16",
    },
    {
        id: 18,
        title: "The Odyssey",
        authors_ids: "5",
        item_type: "book",
        published_date: "8th century BCE",
    },
    {
        id: 19,
        title: "The Iliad",
        authors_ids: "1",
        item_type: "book",
        published_date: "8th century BCE",
    },
    {
        id: 20,
        title: "The Divine Comedy",
        authors_ids: "2",
        item_type: "book",
        published_date: "1320",
    },
];